name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      SITE_URL: localhost:3000

    steps:
    - uses: actions/checkout@v2
    - name: Create config directory
      run: mkdir -p ~/.config/google-chrome
    - name: Build web Docker container
      working-directory: ./gitactions.ci-test.web
      run: docker build -t testweb:latest -f ./Dockerfile -m 4g .
    - name: Run local container
      run: docker run --rm -v ${PWD}:/app -v /app/node_modules -p 3000:3000 -e CHOKIDAR_USEPOLLING=true testweb:latest
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download chromedriver
      uses: wei/curl@master
      with:
        args: https://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip -o ./gitactions.ci-test.UITesting/chromedriver_linux64.zip
    - name: Unzip chromedriver
      working-directory: ./gitactions.ci-test.UITesting
      run: unzip chromedriver_linux64.zip
    - name: Set permissions
      working-directory: ./gitactions.ci-test.UITesting
      run: chmod 774 ./chromedriver
    - name: Restore dotnet project
      working-directory: ./gitactions.ci-test.UITesting
      run: dotnet restore
    - name: Build
      working-directory: ./gitactions.ci-test.UITesting
      run: dotnet build --no-restore
    - name: Move chromedriver to bin/Debug/net5.0
      working-directory: ./gitactions.ci-test.UITesting
      run: mv ./chromedriver ./bin/Debug/net5.0/
    - name: Test
      working-directory: ./gitactions.ci-test.UITesting
      run: dotnet test --no-build --verbosity normal
